### ISSUE TITLE
Trouble After Update

### ISSUE THREAD

**Issue by jedichrome** [Zero6992/Zero6992#11]
I setup the newest build today and I can't get it to launch?

root@localhost:~/chatgpt/chatGPT-discord-bot-main# python3 main.py
Traceback (most recent call last):
  File "/root/chatgpt/chatGPT-discord-bot-main/main.py", line 3, in <module>
    from src import bot
  File "/root/chatgpt/chatGPT-discord-bot-main/src/bot.py", line 7, in <module>
    from g4f.client import Client
ModuleNotFoundError: No module named 'g4f'

**Comment by Zero6992** [comment]
`pip install -r requirements.txt`

**Comment by jedichrome** [comment]
I did that but I didn't notice this error the first time:

ERROR: Cannot uninstall 'blinker'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

**Comment by jedichrome** [comment]
ah, fixed-- 

sudo apt remove python3-blinker
